### ISSUE TITLE
Should correlation / artificial context be handled in "run" instead of "init" ?

### ISSUE THREAD

**Issue by Guillaume-Fourrat** [LazaUK/AzureML-Monitoring-DataCollector#1]
At https://github.com/LazaUK/AzureML-Monitoring-DataCollector/blob/41e19dd73c3fcfbbdfa22d2d66ed882f9c9bc8da/onlinescoring/score_datacollector.py#L21 

Shouldn't that be instantiated and populated in "Run" (ie for each inference invocation) instead of "init" to provide _each query_ a distinctive correlation context ?

See https://learn.microsoft.com/en-us/azure/machine-learning/how-to-collect-production-data?view=azureml-api-2&tabs=azure-cli#update-your-scoring-script-to-log-custom-unique-ids

That said from logs, the resulting context is 
""correlationid":"Laziz_Demo""

So I wonder how much "uniqueness" the BasicCorrelationContext is bringing ?!

Went ahead and pulled code from https://pypi.org/project/azureml-ai-monitoring/#files

```
class BasicCorrelationContext(CorrelationContext):
    # pylint: disable=redefined-builtin
    def __init__(self, id: str = None, timestamp: int = None, headers=None):
        super().__init__()
        self.id = id if id else str(uuid.uuid4())
        self.timestamp = timestamp if timestamp else int(time.time())
        self.headers = headers if headers else {}
    # pylint: enable=redefined-builtin

    def get_id(self) -> str:
        return self.id

    def get_timestamp(self) -> int:
        return self.timestamp

    def get_headers(self) -> dict:
        return self.headers
```

so if we provide a string, the string is used "as is" instead of using a unique GUID
furthermore we see timestamp material getting created as well => I wonder if this could be the cause for the "same timestamp" for all queries issue ?!

```
from azureml.ai.monitoring.context import BasicCorrelationContext
import time
artificial_context = BasicCorrelationContext(id='Laziz_Demo')
print("artificial_context: "+str(artificial_context))
print("artificial_context timestamp: "+str(artificial_context.get_timestamp()))
time.sleep(2)
artificial_context2 = BasicCorrelationContext()
print("artificial_context2: "+str(artificial_context2))
print("artificial_context2 timestamp: "+str(artificial_context2.get_timestamp()))
```

Results :

artificial_context: Laziz_Demo
artificial_context timestamp: 1732011737
artificial_context2: d9077c6e-e2ba-4774-85f5-b2665351faef
artificial_context2 timestamp: 1732011739

So clearly we're not creating any unique per-query correlationID using  BasicCorrelationContext(id='Laziz_Demo'), and we might also get a static timestamp from the time the code is instantiated ...

**Comment by LazaUK** [comment]
Thank you for your feedback, Guillaume. Yes, both options are feasible. And there is a caveat:
- when using something static, like "Laziz_Demo" in this case, it's a better fit for **init()** as it would remain the same;
- if uniqueness is required per each execution, then correlation context can be added to **run()** and "static text" extended with unique GUIDs, to bring extra value to its reflection and logging.

**Comment by Guillaume-Fourrat** [comment]
Tested the change and I'm confident it belongs to "run" as it did solve the "static timestamp for all queries" situation. Created PR #2
